### ISSUE TITLE
collinearity of variables

### ISSUE THREAD

**Issue by k-sanchez** [meganlsmith/delimitR-manual#11]
Dear Megan, first of all, thanks for the contribution you made with this package, I found it extremely useful for exploring recent divergences
I was having a problem when building the RF classifier:
`In lda.default(x, grouping, ...) : variables are collinear`

I think this is problematic for inferences. What could be the solution to this problem?

thanks in advance

**Comment by meganlsmith** [comment]
Hi Kevin,

Glad you have found the package helpful! This warning is not surprising. Part of the reason that we use Random Forests is because we expect that bins of the SFS will be correlated, and RF are relatively robust to this issue. This collinearity means you cannot trust measures of variable importance as much, perhaps, but these are not interpreted in delimitR anyway. There is no clear solution to this though, and we still found high predictive power in simulations. 

Best,
Megan
Megan Smith
NSF Postdoctoral Fellow
Department of Biology
Indiana University, Bloomington, IN

**Comment by k-sanchez** [comment]
Thanks for the clear reply!
Best wishes
