### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by isisarantes** [meganlsmith/delimitR-manual#3]
Hi Megan,

I'm using the new version of R and I'm not able to install it using:

> devtools::install('delimitR', dependencies = TRUE)
Error: Can't find 'delimitR'.

or 

R CMD INSTALL /Users/isisarantes/Downloads/delimitR_2.0.1.tar.gz 
* installing to library ‘/Users/isisarantes/Library/R/3.6/library’
* installing *source* package ‘delimitR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in setwd("~/Desktop/delimitR-master") : 
  cannot change working directory
Error: unable to load R code in package ‘delimitR’
Execution halted
ERROR: lazy loading failed for package ‘delimitR’
* removing ‘/Users/isisarantes/Library/R/3.6/library/delimitR’

Any idea how to fix it?

**Comment by meganlsmith** [comment]
Hi Ísis,

I am working on this issue; It seems to be related to an update I just
push. In the time being, you can use the previous
version delimitR_2.0.0.tar.gz, which should install correctly. The bug I
fixed was related to using a list of guide trees instead of a single guide
tree. Are you planning to use multiple guide trees? Regardless, I hope to
fix this issue and push a new version either later today or tomorrow. Sorry
for any inconvenience.

Best,
Megan

Megan L. Smith
PhD Candidate
Department of Evolution, Ecology, & Organismal Biology
300 Aronoff Labs
The Ohio State University
318 W. 12th Avenue
Columbus, OH 43210-1293

**Comment by meganlsmith** [comment]
Hi Ísis,
Luckily turned out to be a pretty easy fix. I just pushed a new version,
and you should be good to go now. Please let me know if you have other
issues!

Best,
Megan
Megan L. Smith
PhD Candidate
Department of Evolution, Ecology, & Organismal Biology
300 Aronoff Labs
The Ohio State University
318 W. 12th Avenue
Columbus, OH 43210-1293

**Comment by isisarantes** [comment]
Hi Megan,

It worked using the previous version not the new one. 
Using the same command lines:

MacBook-Pro:~ isisarantes$ R CMD INSTALL /Users/isisarantes/Downloads/delimitR_2.0.1.tar.gz
* installing to library ‘/Users/isisarantes/Library/R/3.6/library’
* installing *source* package ‘delimitR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in setwd("~/Desktop/delimitR-master") : 
  cannot change working directory
Error: unable to load R code in package ‘delimitR’
Execution halted
ERROR: lazy loading failed for package ‘delimitR’
* removing ‘/Users/isisarantes/Library/R/3.6/library/delimitR’
* restoring previous ‘/Users/isisarantes/Library/R/3.6/library/delimitR’
(base) MacBook-Pro:~ isisarantes$ R CMD INSTALL /Users/isisarantes/Downloads/delimitR_2.0.0.tar.gz
* installing to library ‘/Users/isisarantes/Library/R/3.6/library’
* installing *source* package ‘delimitR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (delimitR)

or

devtools::install('delimitR', dependencies = TRUE)
Error: Can't find 'delimitR'.

I don't know if yet if I'll use multiple guide trees. 
Thank you :-)
Ísis

**Comment by meganlsmith** [comment]
Hi Ísis,
No problem, glad you pointed this out!

Can you confirm two things:

1) When you redownloaded 2.0.1 from GitHub, did you unpack it in the same
place without deleting the previous directory? The issue was a file I
deleted, so if you unpacked them in the same place, it's possible that the
file got carried over. Try deleting the previous folder, downloading the
newest .tar.gz, unpacking, and installing.
2) What directory are you in when running devtools::install. Make sure that
this is the same directory that the 'delimitR' folder is in, or the install
will fail because it can't find the folder.

Best,
Megan Smith
PhD Candidate
Department of Evolution, Ecology, & Organismal Biology
300 Aronoff Labs
The Ohio State University
318 W. 12th Avenue
Columbus, OH 43210-1293

**Comment by isisarantes** [comment]
Hi Megan,

You were right, I didn't use the correct version. I just did with the right one and it worked.
Thank you!
Ísis

**Comment by meganlsmith** [comment]
You're welcome! Glad it worked. Let me know if you have any other issues/
questions!
Best,
Megan
Megan L. Smith
PhD Candidate
Department of Evolution, Ecology, & Organismal Biology
300 Aronoff Labs
The Ohio State University
318 W. 12th Avenue
Columbus, OH 43210-1293
