### ISSUE TITLE
ValueError: Value list is not the same length as the OrderedDict.

### ISSUE THREAD

**Issue by DevonDeRaad** [meganlsmith/delimitR-manual#5]
Hi, I got the tutorial dataset to run perfectly, but am now getting the error 'ValueError: Value list is not the same length as the OrderedDict.' every time I run makeprior() using my own RAD-seq data. Because I have gotten the same error across multiple python and R installations, I am assuming this comes from an issue with my inputs, specifically my traits file. My traits file matches my downsampled mSFS (12 lines: species 0, 24 lines: species 1), with a header line of 'traits \t species'. I would love any insight into what the source of this error might be and how I can navigate around it. Thanks!

my code:
#delimitr

#setwd("~/Downloads/delimitR-master/")
#devtools::install('delimitR', dependencies = TRUE)
library(delimitR)

#force R to find newest python installation
Sys.setenv(PATH = paste("/Users/devder/opt/miniconda3/bin/", Sys.getenv("PATH"), sep=":"))

#setwd
setwd("~/Desktop/ery.delimitr")

#location of our observed sfs (cannot be full path, must be in wd, drop .obs file extension)
observedSFS <- 'bi_MSFS'

#location of our traits file (2 column file which maps alleles to species, must be in wd)
traitsfile <- 'traits_all.txt'

#guide tree
observedtree <- '(0,1);'

#migration matrix (must be symmetrical)
migmatrix <- matrix(c(FALSE, TRUE,
                      TRUE, FALSE),
                    nrow = 2, ncol = 2, byrow = TRUE)

#test divergence with gene flow?
divwgeneflow <- TRUE

#test secondary contact?
seccontact <- TRUE

#what is the maximum number of migration events to consider on your guide tree?
maxedges <- 1

#how many species are in your guide tree?
obsspecies<- 2

#2x the number of diploid individuals retained after downsampling for SFS
obssamplesize <- c(12,24)

#The user must specify the number of linkage blocks to simulate
#For unlinked SNPs, this is equal to the number of SNPs used to build your observed SFS
obssnps <- 1833

#The user must also provide a prefix
#This will be used to name the fsc2 input files, as well as other output files
#This should be unique for all guide tree + prior combinations in a folder, or files will be overwritten
obsprefix <- 'png.ery.guidetree'

#The user must specify priors on population sizes
#The first vector is for population 0, the second for population 1, and the third for population 2
#Note that these are in terms of the number of haploid individuals (as specified in the fsc2 documentation)
obspopsizeprior <- list(c(10000,100000),c(10000,100000))

#priors for divergence times given in terms of the number of generations and must be supplied as a list of vectors
#Divergence time priors should be provided in order of coalescent interval
obsdivtimeprior <- list(c(1000,100000))

#prior on migration rates, program only allows one prior for all migration rates in the default model sets
obsmigrateprior <- list(c(0.000001,0.01))

#set up your prior models for fastsimcoal2
setup_fsc2(tree=observedtree,
           nspec=obsspecies,
           samplesizes=obssamplesize,
           nsnps=obssnps,
           prefix=obsprefix,
           migmatrix=migmatrix,
           popsizeprior=obspopsizeprior,
           divtimeprior=obsdivtimeprior,
           migrateprior=obsmigrateprior,
           secondarycontact= seccontact,
           divwgeneflow= divwgeneflow,
           maxmigrations = maxedges)

#fastsimcoalsims() requires the prefix used to generate the model files, the path to fastsimcoal2, and num of reps 
#Generally, a minimum of 10,000 replicates under each model should be simulated.
fastsimcoalsims(prefix=obsprefix,
                pathtofsc='~/Downloads/fsc26_mac64/fsc26',
                nreps=10000)

#need to turn our mSFS into a binned (bSFS) specify bin number here
#number should not be greater than the sample size of the population with the fewest samples, as this results in sparse sampling of the SFS
#Large values lead to a more complete summary of the data, but also lead to a more sparsely sampled SFS and increased computation times
nclasses <- 6

#to make prior, provide:
#prefix used to name the model files, the number of species, the number of classes to be included in the SFS,
#a path to the working directory, the name of the traits file, the threshold,
#the name of the folder to store the prior in, and the number of cores to use.

FullPrior <- makeprior(prefix=obsprefix,
                       nspec=obsspecies,
                       nclasses=nclasses,
                       getwd(),
                       traitsfile = traitsfile,
                       threshold = 50,
                       thefolder = 'Prior',
                       ncores = 1)

#remove extraneous files
#clean_working(prefix=obsprefix)

#remove invariant data
ReducedPrior <- Prior_reduced(FullPrior)

#build random forest
myRF <- RF_build_abcrf(ReducedPrior,FullPrior,500)
myRF
classification.error<-myRF[["model.rf"]]$confusion.matrix
plot(myRF, training = ReducedPrior)

#prep data
myobserved <- prepobserved(
  observedSFS,
  FullPrior,
  ReducedPrior,
  nclasses,
  obsspecies,
  traitsfile=traitsfile,
  threshold = 100)

#Now, we're ready to apply the RF classifier to the observed data.
#we use the function RF_predict_abcrf(), which requires the RF object, the observed dataset,
#the Reduced Prior, the Full Prior, and the number of trees, which should match that used to construct the classifier
prediction <- RF_predict_abcrf(myRF, myobserved, ReducedPrior, FullPrior, 500)
prediction

**Comment by meganlsmith** [comment]
Hi Devon,

Thanks for posting and for including your code. Would you mind attaching
your traits file, and your observed SFS; generally this is where the issue
is with this particular error. Thanks!

Best,
Megan
Megan L. Smith, PhD
Postdoctoral Researcher
Department of Biology
Indiana University

**Comment by DevonDeRaad** [comment]
[traits_all.txt](https://github.com/meganlsmith/delimitR/files/4899550/traits_all.txt)

[bi_MSFS.obs.txt](https://github.com/meganlsmith/delimitR/files/4899556/bi_MSFS.obs.txt)

These are my two input files (added a .txt extension to the file 'bi_MSFS.obs' so that it could be uploaded through this comment box).

Thanks!
Devon

**Comment by meganlsmith** [comment]
Hi Devon,

Thanks. I think the issue is the threshold. Why is it set to 50? What
software did you use to build your SFS? This bit can be a bit clunky across
preprocessing methods; sorry for the confusion!
Best,
Megan
Megan L. Smith, PhD
Postdoctoral Researcher
Department of Biology
Indiana University

**Comment by DevonDeRaad** [comment]
I used easySFS to build the SFS, and I set the threshold to 50 because that was the cutoff for missing data to retain a locus in the rad dataset that was input to easySFS for downsampling. I tried running with threshold set to 50 and 100, but I receive the same error each time. I wasn't quite sure I was setting the threshold correctly, so any tips would be great.

Thanks!
Devon

**Comment by meganlsmith** [comment]
Hi Devon,

Sorry this took a bit, but it turns out you found a bug that was introduced
with the update to Python 3 that I made a couple of weeks ago. It is fixed
now, and you should not get that error anymore. You'll just need to
redownload and install delimitR from GitHub. Sorry for the inconvenience,
and thanks for finding this and sharing it with me!

Best,
Megan
Megan L. Smith, PhD
Postdoctoral Researcher
Department of Biology
Indiana University

**Comment by DevonDeRaad** [comment]
Hi Megan, thanks so much for the responsiveness and quick update. With the new version, I have found that if I set threshold to 100 it runs perfectly, but if I set threshold to 50, I get the same ValueError. Could you give me any insight into how I should be setting the threshold value, or what effect it might have in my analysis?

Thanks again for your helpfulness on this,
Devon

**Comment by meganlsmith** [comment]
Hi Devon,

Of course; I'm glad you caught this!

The threshold is in place so that, if you downsampled, so your traits file
doesn't match the number of individuals in the SFS, then it will still
work. However, this works based on haplotypes, not diploid individuals.
Since you downsampled to 50%, but you only had one line per individual in
the traits file (rather than 2, if you were coding based on haplotypes),
your traits file actually matched your down sampling (the individual labels
won't affect anything at this point, so it's fine that your traits file is
this way.) This is a bit clunky admittedly. The scripts I've traditionally
used to build the SFS required the traits file to have two lines per
diploid individual, and this is why it was initially set up this way.
However, I'm reluctant to change it, because I want delimitR to remain
usable to those working with organisms with different ploidy levels. Hope
this makes sense; let me know if it's still unclear! Long story short, you
should use a threshold of 100, and it will not affect your analysis.

Best,
Megan
Megan L. Smith, PhD
Postdoctoral Researcher
Department of Biology
Indiana University

**Comment by DevonDeRaad** [comment]
That is super helpful, thank you so much for the attentiveness, looking forward to implementing the program!

**Comment by meganlsmith** [comment]
Great, thanks Devon! Let me know if you have any other questions!
Best,
Megan
Megan L. Smith, PhD
Postdoctoral Researcher
Department of Biology
Indiana University
